### ISSUE TITLE
Get fixtures working.

### ISSUE THREAD

**Issue by jacebrowning** [votealign/votealign#27]
If I run `make clean all` in 289f2829292acc42321b9471117d72590f07f92f there is an error loading initial data:

```
...
- Loading initial data for askbot.
...
  File "/Users/Browning/Programs/Websites/VoteAlign/votealign/env/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
DoesNotExist: Post matching query does not exist.
...
```

@Crevax any idea what this means?

**Comment by Crevax** [comment]
Looks like I had some of the ordering mixed up, which didn't matter if there was previously generated data (I manually added a post and did a diff of the dump before and after to see what all was needed in the fixture. New fixture works.

**Comment by jacebrowning** [comment]
Thanks!
